cdecl: add test harness for checking program output
In order to keep a record of the program's current behavior during refactoring,
create a test harness which compares the contents of the output stream to that
which the binary currently produces.

Notable observations during development include:

0. fread() returns 0 and does not copy characters to the provided string if the
   number of characters in the stream is less than the requested number.   There is
   no error.

1. The only sane way to invoke glibc's getline() is by providing it with a
   char** pointer with no backing allocation.  Allocating a buffer results in a
   leak since getline() changes the address of the pointer.  Saving the original
   value of the pointer and freeing that on exit *still* results in a memory
   leak, this time from glibc, which internally allocates the returned buffer.

2. It's not necessary to append a newline to the stream which getline() reads as
   long as the stream is flushed.

3. Any googletest function which returns a value cannot contain an assertion, as
   an assertion prevents the value from being returned.  The odd error message
   is
   cdecl_testsuite.cc:216:5: error: void value not ignored as it ought to be
      ASSERT_THAT(fflush(fake_stdout), ::testing::Gt(0));